apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonar-scanner
  name: sonar-scanner
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sonar-scanner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sonar-scanner
    spec:
      containers:
        - image: xiuxianli/sonar_scanner
          imagePullPolicy: IfNotPresent
          name: sonar-scanner
          ports:
            - containerPort: 9000
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
