apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hadoop-master-node
  name: hadoop-master-node-lb
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9870
  selector:
    app: hadoop-master-node
  sessionAffinity: None
  type: LoadBalancer
