apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: hadoop-worder-node0
  name: hadoop-worder-node0
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hadoop-worder-node0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hadoop-worder-node0
    spec:
      containers:
        - image: xiuxianli/hadoop_worker
          ports:
            - containerPort: 9864
              protocol: TCP
          imagePullPolicy: IfNotPresent
          name: hadoop-worder-node0
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
