apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: hadoop-worker-node0
  name: hadoop-worker-node0
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 9864
      protocol: TCP
      targetPort: 9864
  selector:
    app: hadoop-worker-node0
  sessionAffinity: None
  type: NodePort