kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-worker0
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker0
  template:
    metadata:
      labels:
        component: spark-worker0
    spec:
      containers:
        - name: spark-worker0
          image: xiuxianli/spark
          command:
            [
              "/spark-worker",
            ]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
