apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "toolbox-app"
  namespace: "default"
  labels:
    app: "toolbox-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "toolbox-app"
  template:
    metadata:
      labels:
        app: "toolbox-app"
    spec:
      containers:
      - name: "toolbox-app-1"
        image: "gcr.io/banded-anvil-327600/toolbox-app:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "toolbox-app-hpa-pwdh"
  namespace: "default"
  labels:
    app: "toolbox-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "toolbox-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80